receivers:
  - name: "teams"
    msteamsv2_configs:
      - webhook_url: "https://netspextechnologiesllp.webhook.office.com/webhookb2/f209c001-d0f5-4b27-8b44-47d077e94f96@62e46a17-fc11-49a6-bd87-01cc14bb0f22/IncomingWebhook/f72072f3fd2a4a1a89025cb2a06978ca/549fce7a-9a73-47ef-86e4-415b2a1e8972/V2h0XfbhpnI8zrytkQU_Jn7SxIEsour259_LwJncxU3ew1"
        send_resolved: true

        title: '{{ .CommonAnnotations.summary }}'

        text: |
          🚨 **Alert:** {{ .CommonLabels.alertname }}
          **Severity:** {{ .CommonLabels.severity }}
          **Instance:** {{ .CommonLabels.instance }}

          **Description:**
          {{ .CommonAnnotations.description }}

          **Starts At:** {{ .StartsAt }}
