receivers:
  - name: teams
    msteamsv2_configs:
      - webhook_url: "https://your-webhook-url"
        send_resolved: true
        title: "{{ .CommonAnnotations.summary }}"
        text: |
          🚨 Alert: {{ .CommonLabels.alertname }}
          Severity: {{ .CommonLabels.severity }}
          Instance: {{ .CommonLabels.instance }}

          {{ .CommonAnnotations.description }}

  - name: email
    email_configs:
      - to: "gundurao@kevitco.com"
        from: "gundurao@kevitco.com"
        smarthost: "smtp.company.com:587"
        auth_username: "gundurao@kevitco.com"
        auth_password: "Kulk@rn1"
        require_tls: true
        send_resolved: true
